version: 1.0.{build}
os: Visual Studio 2017
platform: x64
clone_folder: C:\projects\arbitrary_precision
shallow_clone: true
branches:
  only:
    - master
environment:
  matrix:
  - config: Debug
build:
  parallel: true
build_script:
  - cd c:\projects\arbitrary_precision
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%config% -G "Visual Studio 15 2017 Win64" ../
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=%config% /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% ArbitraryPrecision.sln

test_script:
  - cd c:\projects\arbitrary_precision\build\tests
  - .\unit_tests.exe