dist: trusty
sudo: required
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - xorg-dev
    - libglu1-mesa-dev
    - libsuitesparse-dev
matrix:
  include:
  - os: linux
    compiler: gcc-7
    env:
    - MATRIX_EVAL="export CC=gcc-7 && CXX=g++-7 && CONFIG=Debug"
  - os: osx
    osx_image: xcode8.3
    compiler: clang
    env:
    - MATRIX_EVAL="export CONFIG=Debug"
  - os: osx
    osx_image: xcode9.4
    compiler: clang
    env:
    - MATRIX_EVAL="export CONFIG=Debug"
  - os: osx
    osx_image: xcode10.2
    compiler: clang
    env:
    - MATRIX_EVAL="export CONFIG=Debug"

install:
- eval "${MATRIX_EVAL}"

script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=$CONFIG ..
- make -j2
- make test
- cd ..
